import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1734671636477 implements MigrationInterface {
    name = 'InitialMigration1734671636477'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` ADD \`context\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuAuthority_Table\` DROP FOREIGN KEY \`FK_5235f59465c2873e5220b5f047f\``);
        await queryRunner.query(`ALTER TABLE \`dbo_menuAuthority_Table\` CHANGE \`createdBy\` \`createdBy\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuAuthority_Table\` CHANGE \`updatedBy\` \`updatedBy\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuAuthority_Table\` CHANGE \`menuMenuID\` \`menuMenuID\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`parent\` \`parent\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`menuURL\` \`menuURL\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`cssParent\` \`cssParent\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`cssClass\` \`cssClass\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`aClass\` \`aClass\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`dataToggle\` \`dataToggle\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`context\` \`context\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`slNum\` \`slNum\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`colDef\` \`colDef\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`wsName\` \`wsName\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`vwName\` \`vwName\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`functionName\` \`functionName\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`functionType\` \`functionType\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`owner\` \`owner\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`rejectReason\` \`rejectReason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`caption\` \`caption\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`guide\` \`guide\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`createdBy\` \`createdBy\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`updatedBy\` \`updatedBy\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` DROP FOREIGN KEY \`FK_543ad7498ad1aba498d0ade4f56\``);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` DROP FOREIGN KEY \`FK_ac8007ad75f640d4a21ccf0f434\``);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` CHANGE \`createdBy\` \`createdBy\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` CHANGE \`updatedBy\` \`updatedBy\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` CHANGE \`roleEntityRole\` \`roleEntityRole\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` CHANGE \`menuEntityMenuID\` \`menuEntityMenuID\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`home\` \`home\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`priority\` \`priority\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`maxSessions\` \`maxSessions\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`inactivityTimeout\` \`inactivityTimeout\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`passwordFailLimit\` \`passwordFailLimit\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`nFAFailLimit\` \`nFAFailLimit\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`orgId\` \`orgId\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`isPartnerRole\` \`isPartnerRole\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`owner\` \`owner\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`description\` \`description\` varchar(400) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`expirationDuration\` \`expirationDuration\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`accntLockDuration\` \`accntLockDuration\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`resetAccntCounter\` \`resetAccntCounter\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`chCapacity\` \`chCapacity\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`displayName\` \`displayName\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`createdBy\` \`createdBy\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`updatedBy\` \`updatedBy\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` DROP FOREIGN KEY \`FK_fdefc9461e7fba262d2f9669c32\``);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`authorityID\` \`authorityID\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`canView\` \`canView\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`canChange\` \`canChange\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`canDelete\` \`canDelete\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`createdBy\` \`createdBy\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`updatedBy\` \`updatedBy\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`roleRole\` \`roleRole\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuAuthority_Table\` ADD CONSTRAINT \`FK_5235f59465c2873e5220b5f047f\` FOREIGN KEY (\`menuMenuID\`) REFERENCES \`dbo_menuDef_Table\`(\`menuID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` ADD CONSTRAINT \`FK_543ad7498ad1aba498d0ade4f56\` FOREIGN KEY (\`roleEntityRole\`) REFERENCES \`dbo_Roles_Table\`(\`role\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` ADD CONSTRAINT \`FK_ac8007ad75f640d4a21ccf0f434\` FOREIGN KEY (\`menuEntityMenuID\`) REFERENCES \`dbo_menuDef_Table\`(\`menuID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` ADD CONSTRAINT \`FK_fdefc9461e7fba262d2f9669c32\` FOREIGN KEY (\`roleRole\`) REFERENCES \`dbo_Roles_Table\`(\`role\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` DROP FOREIGN KEY \`FK_fdefc9461e7fba262d2f9669c32\``);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` DROP FOREIGN KEY \`FK_ac8007ad75f640d4a21ccf0f434\``);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` DROP FOREIGN KEY \`FK_543ad7498ad1aba498d0ade4f56\``);
        await queryRunner.query(`ALTER TABLE \`dbo_menuAuthority_Table\` DROP FOREIGN KEY \`FK_5235f59465c2873e5220b5f047f\``);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`roleRole\` \`roleRole\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`updatedBy\` \`updatedBy\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`createdBy\` \`createdBy\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`canDelete\` \`canDelete\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`canChange\` \`canChange\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`canView\` \`canView\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` CHANGE \`authorityID\` \`authorityID\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_roleAuthority_Table\` ADD CONSTRAINT \`FK_fdefc9461e7fba262d2f9669c32\` FOREIGN KEY (\`roleRole\`) REFERENCES \`dbo_Roles_Table\`(\`role\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`updatedBy\` \`updatedBy\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`createdBy\` \`createdBy\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`displayName\` \`displayName\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`chCapacity\` \`chCapacity\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`resetAccntCounter\` \`resetAccntCounter\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`accntLockDuration\` \`accntLockDuration\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`expirationDuration\` \`expirationDuration\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`description\` \`description\` varchar(400) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`owner\` \`owner\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`isPartnerRole\` \`isPartnerRole\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`orgId\` \`orgId\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`nFAFailLimit\` \`nFAFailLimit\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`passwordFailLimit\` \`passwordFailLimit\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`inactivityTimeout\` \`inactivityTimeout\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`maxSessions\` \`maxSessions\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`priority\` \`priority\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` CHANGE \`home\` \`home\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` CHANGE \`menuEntityMenuID\` \`menuEntityMenuID\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` CHANGE \`roleEntityRole\` \`roleEntityRole\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` CHANGE \`updatedBy\` \`updatedBy\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` CHANGE \`createdBy\` \`createdBy\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` ADD CONSTRAINT \`FK_ac8007ad75f640d4a21ccf0f434\` FOREIGN KEY (\`menuEntityMenuID\`) REFERENCES \`dbo_menuDef_Table\`(\`menuID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dbo_RoleMenu_Table\` ADD CONSTRAINT \`FK_543ad7498ad1aba498d0ade4f56\` FOREIGN KEY (\`roleEntityRole\`) REFERENCES \`dbo_Roles_Table\`(\`role\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`updatedBy\` \`updatedBy\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`createdBy\` \`createdBy\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`guide\` \`guide\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`caption\` \`caption\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`rejectReason\` \`rejectReason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`owner\` \`owner\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`functionType\` \`functionType\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`functionName\` \`functionName\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`vwName\` \`vwName\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`wsName\` \`wsName\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`colDef\` \`colDef\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`slNum\` \`slNum\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`context\` \`context\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`dataToggle\` \`dataToggle\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`aClass\` \`aClass\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`cssClass\` \`cssClass\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`cssParent\` \`cssParent\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`menuURL\` \`menuURL\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuDef_Table\` CHANGE \`parent\` \`parent\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuAuthority_Table\` CHANGE \`menuMenuID\` \`menuMenuID\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuAuthority_Table\` CHANGE \`updatedBy\` \`updatedBy\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuAuthority_Table\` CHANGE \`createdBy\` \`createdBy\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`dbo_menuAuthority_Table\` ADD CONSTRAINT \`FK_5235f59465c2873e5220b5f047f\` FOREIGN KEY (\`menuMenuID\`) REFERENCES \`dbo_menuDef_Table\`(\`menuID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`dbo_Roles_Table\` DROP COLUMN \`context\``);
    }

}
